### ISSUE TITLE
Platz lassen für Klebeband

### ISSUE THREAD

**Issue by bronsen** [shackspace/tag-generator#3]
Da die Tags u.U. mit Klebeband/Tesafilm befestigt werden, soll an geeigneter Stelle Platz gelassen werden auf dem Tag, damit die Klebestreifen keinen relevanten Kontent überkleben.

Vielleicht kann den so freigehaltenen Platz auch durch gestrichelte Linien kenntlich machen; usability und so.

**Comment by makefu** [comment]
On Mon, Dec 17, 2012 at 02:10:15PM -0800, Kalle Bronsen wrote:

> Vielleicht kann den so freigehaltenen Platz auch durch gestrichelte Linien
> kenntlich machen; usability und so.

Ich schlage vor, dass wir die ecken schwarz machen und somit andeuten wo
geklebt werden soll.

**Comment by Phrewfuf** [comment]
On Mon, 17 Dec 2012 14:29:37 -0800, Felix Richter
notifications@github.com wrote:

> On Mon, Dec 17, 2012 at 02:10:15PM -0800, Kalle Bronsen wrote:
> 
> > Vielleicht kann den so freigehaltenen Platz auch durch gestrichelte
> > Linien
> > kenntlich machen; usability und so.
> 
> Ich schlage vor, dass wir die ecken schwarz machen und somit andeuten wo
> geklebt werden soll.

Warum nicht einfach die Leute transparentes Tape verwenden lassen? :D

## 

Mit freundlichen Grüßen / Best regards
Andreas Kist

me@andreaskist.de

**Comment by bronsen** [comment]
wir haben Platz gelassen für durchsichtige und opakes Klebeband
