### ISSUE TITLE
Layout: Tags sollen einen Rahmen besitzen

### ISSUE THREAD

**Issue by makefu** [shackspace/tag-generator#5]
Fuers ausdrucken sollen die tags einen dezenten rahmen haben, damit man ungefaehr weiss wo man ausschneiden muss.

**Comment by bronsen** [comment]
Ist das relephant bei A4?

**Comment by makefu** [comment]
Definitiv, da wir ja normaler weise nicht A4, sondern $kleiner
ausdrucken werden. Rahmen ist uebrigens umgesetzt.
